@startuml
skinparam Shadowing true
skinparam RoundCorner 5
skinparam MaxMessageSize 250
participant "frontend" as FE #FFF2CC
boundary "api-gateway" as GW #FEF9E7
participant "auth-service" as Auth #EBF5FB
participant "target-service" as TS #F4ECF7
autonumber "<b>0</b>"
group #LightCyan Авторизация и маршрутизация
    FE -> GW: Запрос к защищенному ресурсу
    activate FE #White
    activate GW
    GW -> GW: Поиск JwtValidation в application.yml
GW->GW:Проверка заголовка Authorization
    GW -> Auth: GET {host}/validate
    activate Auth
    Auth->Auth: Валидация JWT
    Auth --> GW: 200 OK
    deactivate Auth
    GW -> TS: Проксирование запроса
    activate TS
    TS->TS: Выполнение\nбизнес логики
    TS --> GW: Ответ
    deactivate TS
    GW --> FE: Проксирование ответа
    deactivate GW
    FE -> FE: Обработка данных,\n отображение ответа\n пользователю
    end
@enduml