@startuml
skinparam Shadowing true
skinparam RoundCorner 5
skinparam MaxMessageSize 250
participant "frontend" as FE #FFF2CC
boundary "api-gateway" as GW #FEF9E7
participant "auth-service" as Auth #EBF5FB
database "auth-db" as DB #EAFAF1
autonumber "<b>0</b>"
group #LightCyan Аутентификации
    FE -> GW: POST {host}/auth/login
    activate FE #White
    activate GW
    GW -> Auth: Проксирование запроса
    activate Auth
    Auth -> Auth: Валидация входных параметров
    Auth -> DB: Поиск в базе данных: совпадение по email
    activate DB
    DB --> Auth: Данные найдены
    deactivate DB
    Auth -> Auth: Сравнение пароля с хэшем из базы данных (BCrypt)
Auth -> Auth: Генерация JWT
    Auth --> GW: HTTP 200 OK + JWT
    deactivate Auth
    GW --> FE: Проксирование ответа
    deactivate GW
    FE -> FE: Сохранение в localStorage JWT и редирект на главную страницу
    end
    deactivate FE

@enduml