@startuml
skinparam Shadowing true
skinparam RoundCorner 5
skinparam MaxMessageSize 250

boundary "API Consumer" as AC #FEF9E7

box "patient-service" #5D6D7E
    participant "DispatcherServlet" as DS #White
    participant "Jackson" as Jackson #White
    participant "PatientController" as Ctrl #White
    participant "PatientService" as Service #White
    participant "PatientRepository" as Repo #White
    participant "PatientMapper" as Mapper #White
end box

database "patient_db" as DB #LightBlue

group #LightCyan Процесс получения списка пациентов\nВнешний URL: GET {gateway-host}/api/patients → Внутренний URL: GET patient-service:4000/patients

    AC -> DS ++: **[1]** GET /patients

    DS -> Ctrl ++: **[2]** getPatients()
    Ctrl -> Service ++: **[3]** getPatients()
    Service -> Repo ++: **[4]** findAll()\n(делегируется SimpleJpaRepository Proxy)
    Repo -> DB ++: **[5]** SELECT * FROM patient\n(Hibernate → HikariCP → JDBC Driver)

    alt #MistyRose Ошибка БД (недоступность / таймаут соединения)
        DB --[#red]> Repo: <color:#red>SQLException</color>
        Repo --[#red]> Service: <color:#red>DataAccessException</color>
        Service --[#red]> Ctrl: <color:#red>DataAccessException</color>
        Ctrl --[#red]> DS: <color:#red>DataAccessException</color>
        DS --[#red]> AC: <color:#red>500 INTERNAL SERVER ERROR</color>
    end

    DB --> Repo --: **[6]** ResultSet

    Repo -> Repo: **[7]** Hydration\n(ResultSet → List<Patient>)
    Repo --> Service --: List<Patient>

    Service -> Mapper ++: **[8]** toDTO(patient)\n(Stream API, для каждого элемента)

    alt #MistyRose Ошибка маппинга
        Mapper --[#red]> Service: <color:#red>RuntimeException</color>
        Service --[#red]> Ctrl: <color:#red>RuntimeException</color>
        Ctrl --[#red]> DS: <color:#red>RuntimeException</color>
        DS --[#red]> AC: <color:#red>500 INTERNAL SERVER ERROR</color>
    end

    Mapper --> Service --: PatientResponseDTO

    Service --[#green]> Ctrl --: **[9]** List<PatientResponseDTO>
    Ctrl --[#green]> DS --: **[10]** ResponseEntity.ok(patients)

    DS -> Jackson ++: **[11]** Сериализация (List<DTO> -> JSON)
    Jackson --> DS --: JSON

    DS --[#green]> AC --: **[12]** 200 OK (JSON)
    deactivate Repo
    deactivate Mapper

end
@enduml
