@startuml
skinparam Shadowing true
skinparam RoundCorner 5
skinparam MaxMessageSize 250

box "patient-service" #5D6D7E
    participant "PatientService" as PS #White
    participant "KafkaProducer" as Producer #White
    participant "KafkaTemplate" as KT #White
end box

queue "Kafka\ntopic: patient" as KF #FADBD8

group #LightCyan Публикация события PatientEvent\npatient-service → Kafka topic: patient

    PS -> Producer ++: **[1]** sendEvent(patient)

    Producer -> Producer: **[2]** PatientEvent.newBuilder()\n.setPatientId(patient.getId())\n.setName(patient.getName())\n.setEmail(patient.getEmail())\n.setEventType("PATIENT_CREATED")\n.build()

    Producer -> Producer: **[3]** event.toByteArray()\n(protobuf-java → byte[])

    Producer -> KT ++: **[4]** kafkaTemplate.send("patient", byte[])\nKey: null

    KT -> KF ++: **[5]** TCP → Kafka broker\ntopic: patient

    alt #MistyRose Kafka недоступен / таймаут
        KF --[#red]> KT: <color:#red>Exception</color>
        KT --[#red]> Producer: <color:#red>Exception</color>

        Producer -> Producer: <color:#red>catch(Exception e)\nlog.error("Error sending PatientCreated event: {}", event)</color>
        note right of Producer: **Data Inconsistency:**\nДанные сохранены в patient_db,\ngRPC-вызов выполнен,\nсообщение в Kafka потеряно.\nКлиент получит 200 OK.
    end

    KF --[#green]> KT --: RecordMetadata (Ack)
    KT --[#green]> Producer --: void

    Producer --> PS --: **[6]** void

end
@enduml
