@startuml
skinparam Shadowing true
skinparam RoundCorner 5
skinparam MaxMessageSize 250
skinparam Style strictuml

participant "Single Page Application" as SPA #LightBlue

box "api-gateway" #FEF9E7
    participant "Route Configuration" as RC #D5E8D4
    participant "JwtValidation Filter" as Filter #FADBD8
    participant "WebClient" as WC #D6EAF8
end box

participant "auth-service" as Auth #EBF5FB
participant "target-service" as TS #F4ECF7

autonumber "<b>[0]</b>"
autonumber stop

group #LightCyan Проксирование к защищенным ресурсам
    SPA -> RC: HTTP Request (порт 4004)
    activate SPA
    activate RC

autonumber resume
    RC -> RC: Поиск маршрута:\nJwtValidation filter FOUND

    RC -> Filter: Передача управления фильтру
    activate Filter

    Filter -> Filter: Извлечение Bearer <token>

    alt #MistyRose Токен отсутствует или неверный формат
        autonumber stop
        Filter --[#red]> SPA: <color:#red>401 UNAUTHORIZED</color>
        autonumber resume
    else #LightCyan Токен извлечен

        Filter -> WC: Инициировать запрос к Auth
        activate WC

        WC -> Auth: GET /validate
        activate Auth

        alt #MistyRose Ошибка связи с Auth Service
            autonumber stop
            Auth --[#red]> WC: <color:#red>Connection Error</color>
            WC --[#red]> SPA: <color:#red>500 INTERNAL SERVER ERROR</color>
            autonumber resume
        else #MistyRose Токен невалиден
            autonumber stop
            Auth --[#red]> WC: <color:#red>401 UNAUTHORIZED</color>
            WC --[#red]> SPA: <color:#red>401 UNAUTHORIZED</color>
            autonumber resume
        else #LightCyan Токен валиден
            Auth --> WC: 200 OK
            deactivate Auth

            WC --> Filter: Validation Success
            deactivate WC

            Filter -> TS: Proxy Request
            activate TS

            alt #MistyRose Целевой сервис недоступен
                autonumber stop
                TS --[#red]> Filter: <color:#red>Error / Timeout</color>
                Filter --[#red]> SPA: <color:#red>500 INTERNAL SERVER ERROR</color>
                autonumber resume
            else #LightGreen Успешный ответ
                TS --> Filter: HTTP Response
                deactivate TS

                Filter --> SPA: Proxy Response
            end
        end
    end

    deactivate Filter
    deactivate RC
    deactivate SPA
end
@enduml