@startuml
skinparam Shadowing true
skinparam RoundCorner 5
skinparam MaxMessageSize 250

box "patient-service" #D5DBDB
    participant "BillingGrpcClient" as PS #White
end box

box "billing-service" #5D6D7E
    participant "Netty" as Netty #White
    participant "Protobuf-java" as Proto #LightYellow
    participant "BillingGrpcService" as BS #White
    participant "BillingResponse.Builder" as Builder #White
end box

group #LightCyan Алгоритм обработки CreateBillingAccount
    PS -> Netty: **[1]** Инициация gRPC-вызова (TCP/HTTP2)
    activate Netty

    alt #MistyRose Ошибка соединения (UNAVAILABLE)
        Netty --[#red]> PS: <color:#red>gRPC Status: 14</color>
    else #HoneyDew Успешное соединение

        Netty -> Netty: **[2]** Прием TCP-пакета и извлечение фреймов

        Netty -> Proto: Передача бинарных данных
        activate Proto
        Proto -> Proto: **[3]** Десериализация в BillingRequest

        alt #MistyRose Ошибка формата (INTERNAL)
            Proto --[#red]> Netty: <color:#red>Exception</color>
            Netty --[#red]> PS: <color:#red>gRPC Status: 13</color>
        else #HoneyDew Успех
            Proto --> Netty: BillingRequest object
            deactivate Proto

            Netty -> BS: **[4]** createBillingAccount(request, responseObserver)
            activate BS

            BS -> BS: **[5]** log.info("request received...")

                BS -> Builder: **[6]** newBuilder()
                activate Builder
                Builder -> Builder: **[7]** setAccountId, setStatus, build()
                Builder --> BS: BillingResponse
                deactivate Builder

            BS -> Netty: **[8]** responseObserver.onNext(response)
            Netty -> Proto: Сериализация объекта
            activate Proto
            Proto --> Netty: binary data
            deactivate Proto

            BS -> Netty: **[9]** responseObserver.onCompleted()
            deactivate BS

            Netty --[#green]> PS: <color:#green> gRPC Status: 0 </color>
            deactivate Netty
        end
    end
end

@enduml