@startuml
skinparam Shadowing true
skinparam RoundCorner 5
skinparam MaxMessageSize 250

boundary "API Consumer" as AC #FEF9E7

box "auth-service" #5D6D7E
    participant "AuthController" as Ctrl
    participant "AuthService" as Service
    participant "JJWT (Library)" as Utils
end box

group #LightCyan Процесс валидации токена (GET /validate)
    AC -> Ctrl: GET /validate (Authorization Header)
    activate Ctrl

    Ctrl -> Ctrl: **[1]** Проверка наличия и формата\nзаголовка (Bearer)

    alt #MistyRose Заголовок отсутствует или неверный префикс
        Ctrl --[#red]> AC: <color:#red>401 UNAUTHORIZED</color>
    else #LightCyan Заголовок корректен

        Ctrl -> Service: **[2]** validateToken(JWT String)
        activate Service

        Service -> Utils: **[3]** Вызов библиотеки (try)
        activate Utils

        note right of Utils
          **[3.1]** Проверка структуры
          **[3.2]** Проверка подписи (Secret Key)
          **[3.3]** Проверка срока действия (exp)
        end note

        alt #MistyRose Выброшено JwtException
            Utils --[#red]> Service: <color:#red>throw JwtException</color>
            Service --[#red]> Ctrl: <color:#red>false (catch)</color>
            Ctrl --[#red]> AC: <color:#red>401 UNAUTHORIZED</color>
        else #LightGreen Валидация успешна
            Utils --> Service: [void/success]
            deactivate Utils

            Service --> Ctrl: true
            deactivate Service

            Ctrl --> AC: **[3]** 200 OK
        end
    end
end

group #WhiteSmoke Системные сбои
    Service --[#red]> Ctrl: <color:#red>Exception (Critical Error)</color>
    Ctrl --[#red]> AC: <color:#red>500 INTERNAL SERVER ERROR</color>
end

deactivate Ctrl
@enduml